/**
 * @module @deepseek-ai/dsh-client-ui-conversation/pet/cet4-vocab-data
 * @description 英语四级 (CET-4) 高频核心乱序词库与智能干扰项生成引擎
 */

export interface Cet4Word {
  word: string
  phonetic: string
  pos: string
  meaning: string
  example: string
}

export const CET4_WORDS: readonly Cet4Word[] = [
  {
    word: 'abandon',
    phonetic: '/əˈbændən/',
    pos: 'v.',
    meaning: '放弃，遗弃，丢弃',
    example: 'He had to abandon his research plan due to a lack of funding.',
  },
  {
    word: 'abnormal',
    phonetic: '/æbˈnɔːml/',
    pos: 'adj.',
    meaning: '反常的，异常的，变态的',
    example: 'The laboratory reported an abnormal increase in temperature.',
  },
  {
    word: 'abundant',
    phonetic: '/əˈbʌndənt/',
    pos: 'adj.',
    meaning: '丰富的，充裕的，大量的',
    example: 'The region is abundant in natural resources like coal and iron.',
  },
  {
    word: 'accelerate',
    phonetic: '/əkˈseləreɪt/',
    pos: 'v.',
    meaning: '加速，促进，加快',
    example: 'New digital technologies will accelerate industrial transformation.',
  },
  {
    word: 'accommodate',
    phonetic: '/əˈkɒmədeɪt/',
    pos: 'v.',
    meaning: '容纳，提供住宿，适应',
    example: 'The newly built hotel can accommodate over one thousand guests.',
  },
  {
    word: 'accumulate',
    phonetic: '/əˈkjuːmjəleɪt/',
    pos: 'v.',
    meaning: '积累，积聚，堆积',
    example: 'She managed to accumulate a large vocabulary through daily reading.',
  },
  {
    word: 'adequate',
    phonetic: '/ˈædɪkwət/',
    pos: 'adj.',
    meaning: '足够的，充足的，适当的',
    example: 'Ensure you have adequate sleep before the final examination.',
  },
  {
    word: 'advocate',
    phonetic: '/ˈædvəkeɪt/',
    pos: 'v.',
    meaning: '主张，拥护，倡导',
    example: 'Environmentalists advocate the use of clean and renewable energy.',
  },
  {
    word: 'allocate',
    phonetic: '/ˈæləkeɪt/',
    pos: 'v.',
    meaning: '分配，分派，拨出',
    example: 'The government decided to allocate more funds to public healthcare.',
  },
  {
    word: 'ambiguous',
    phonetic: '/æmˈbɪɡjuəs/',
    pos: 'adj.',
    meaning: '模棱两可的，含糊不清的',
    example: 'The contract clauses were too ambiguous and led to disputes.',
  },
  {
    word: 'anticipate',
    phonetic: '/ænˈtɪsɪpeɪt/',
    pos: 'v.',
    meaning: '预期，期望，预先考虑',
    example: 'We anticipate that sales will increase significantly next quarter.',
  },
  {
    word: 'apparent',
    phonetic: '/əˈpærənt/',
    pos: 'adj.',
    meaning: '明显的，显而易见的，表面的',
    example: 'It became apparent that the initial hypothesis was incorrect.',
  },
  {
    word: 'applaud',
    phonetic: '/əˈplɔːd/',
    pos: 'v.',
    meaning: '鼓掌，喝彩，称赞',
    example: 'The audience stood up to applaud the wonderful performance.',
  },
  {
    word: 'approximate',
    phonetic: '/əˈprɒksɪmət/',
    pos: 'adj.',
    meaning: '近似的，大约的',
    example: 'Can you give me an approximate estimate of the project cost?',
  },
  {
    word: 'artificial',
    phonetic: '/ˌɑːtɪˈfɪʃl/',
    pos: 'adj.',
    meaning: '人工的，人造的，假的',
    example: 'Artificial intelligence is reshaping numerous modern industries.',
  },
  {
    word: 'assemble',
    phonetic: '/əˈsembl/',
    pos: 'v.',
    meaning: '集合，聚集，装配',
    example: 'Engineers assemble the components carefully on the production line.',
  },
  {
    word: 'attribute',
    phonetic: '/əˈtrɪbjuːt/',
    pos: 'v.',
    meaning: '把…归因于，归咎于',
    example: 'They attribute their academic success to hard work and perseverance.',
  },
  {
    word: 'authentic',
    phonetic: '/ɔːˈθentɪk/',
    pos: 'adj.',
    meaning: '真正的，真实的，可靠的',
    example: 'The museum verified that the ancient manuscript was authentic.',
  },
  {
    word: 'barrier',
    phonetic: '/ˈbæriə(r)/',
    pos: 'n.',
    meaning: '障碍，屏障，栅栏',
    example: 'Language differences should not become a barrier to communication.',
  },
  {
    word: 'beneficial',
    phonetic: '/ˌbenɪˈfɪʃl/',
    pos: 'adj.',
    meaning: '有益的，有帮助的，有利的',
    example: 'Regular physical exercise is beneficial to both body and mind.',
  },
  {
    word: 'boundary',
    phonetic: '/ˈbaʊndri/',
    pos: 'n.',
    meaning: '边界，界限，分界线',
    example: 'The river forms a natural boundary between the two countries.',
  },
  {
    word: 'candidate',
    phonetic: '/ˈkændɪdət/',
    pos: 'n.',
    meaning: '候选人，求职者，考生',
    example: 'She is the most qualified candidate for the software engineer position.',
  },
  {
    word: 'capacity',
    phonetic: '/kəˈpæsəti/',
    pos: 'n.',
    meaning: '容量，能力，才能',
    example: 'The server has the capacity to handle ten thousand concurrent users.',
  },
  {
    word: 'casual',
    phonetic: '/ˈkæʒuəl/',
    pos: 'adj.',
    meaning: '非正式的，随便的，偶然的',
    example: 'Employees are permitted to wear casual clothes on Fridays.',
  },
  {
    word: 'coherent',
    phonetic: '/kəʊˈhɪərənt/',
    pos: 'adj.',
    meaning: '连贯的，一致的，条理清楚的',
    example: 'Her presentation was clear, logical, and coherent throughout.',
  },
  {
    word: 'collaborate',
    phonetic: '/kəˈlæbəreɪt/',
    pos: 'v.',
    meaning: '合作，协作，通力合作',
    example: 'Two prestigious universities decided to collaborate on the AI research.',
  },
  {
    word: 'commercial',
    phonetic: '/kəˈmɜːʃl/',
    pos: 'adj.',
    meaning: '商业的，商务的，盈利的',
    example: 'The invention has great commercial value in the global market.',
  },
  {
    word: 'compensate',
    phonetic: '/ˈkɒmpənseɪt/',
    pos: 'v.',
    meaning: '补偿，赔偿，弥补',
    example: 'Nothing can fully compensate for the loss of valuable historical artifacts.',
  },
  {
    word: 'competent',
    phonetic: '/ˈkɒmpɪtənt/',
    pos: 'adj.',
    meaning: '有能力的，能胜任的，称职的',
    example: 'We need a competent project manager to lead the overseas team.',
  },
  {
    word: 'comprehensive',
    phonetic: '/ˌkɒmprɪˈhensɪv/',
    pos: 'adj.',
    meaning: '全面的，综合的，包罗万象的',
    example: 'The report offers a comprehensive analysis of the economic situation.',
  },
  {
    word: 'compromise',
    phonetic: '/ˈkɒmprəmaɪz/',
    pos: 'n./v.',
    meaning: '妥协，折中，和解',
    example: 'Both sides reached a reasonable compromise after hours of negotiation.',
  },
  {
    word: 'conceal',
    phonetic: '/kənˈsiːl/',
    pos: 'v.',
    meaning: '隐藏，隐瞒，掩盖',
    example: 'He tried to conceal his nervousness during the job interview.',
  },
  {
    word: 'conclude',
    phonetic: '/kənˈkluːd/',
    pos: 'v.',
    meaning: '推断出，下结论，结束',
    example: 'Scientists conclude that the climate change is accelerating globally.',
  },
  {
    word: 'condemn',
    phonetic: '/kənˈdem/',
    pos: 'v.',
    meaning: '谴责，指责，宣判',
    example: 'The international community strongly condemns acts of violence.',
  },
  {
    word: 'confront',
    phonetic: '/kənˈfrʌnt/',
    pos: 'v.',
    meaning: '面临，面对，正视',
    example: 'We must confront these technical challenges courageously.',
  },
  {
    word: 'consequent',
    phonetic: '/ˈkɒnsɪkwənt/',
    pos: 'adj.',
    meaning: '随之发生的，作为结果的',
    example: 'The flood and the consequent crop failure caused a severe food shortage.',
  },
  {
    word: 'conservative',
    phonetic: '/kənˈsɜːvətɪv/',
    pos: 'adj.',
    meaning: '保守的，守旧的，谨慎的',
    example: 'The board took a conservative approach to the investment proposal.',
  },
  {
    word: 'consistent',
    phonetic: '/kənˈsɪstənt/',
    pos: 'adj.',
    meaning: '一致的，连续的，始终如一的',
    example: 'His actions are always consistent with his promised principles.',
  },
  {
    word: 'conspicuous',
    phonetic: '/kənˈspɪkjuəs/',
    pos: 'adj.',
    meaning: '显眼的，引人注目的，突出的',
    example: 'She made conspicuous progress in her English speaking skills.',
  },
  {
    word: 'constant',
    phonetic: '/ˈkɒnstənt/',
    pos: 'adj.',
    meaning: '恒定的，不变的，持续的',
    example: 'The machine operates under constant temperature and pressure.',
  },
  {
    word: 'constitute',
    phonetic: '/ˈkɒnstɪtjuːt/',
    pos: 'v.',
    meaning: '构成，组成，建立',
    example: 'Women constitute more than half of the company\'s management team.',
  },
  {
    word: 'contemplate',
    phonetic: '/ˈkɒntəmpleɪt/',
    pos: 'v.',
    meaning: '沉思，深思熟虑，盘算',
    example: 'He took some time off to contemplate his future career path.',
  },
  {
    word: 'contemporary',
    phonetic: '/kənˈtemprəri/',
    pos: 'adj.',
    meaning: '当代的，现代的，同期的',
    example: 'The gallery exhibits artworks created by contemporary Chinese artists.',
  },
  {
    word: 'contradict',
    phonetic: '/ˌkɒntrəˈdɪkt/',
    pos: 'v.',
    meaning: '反驳，同…矛盾，抵触',
    example: 'The witness\'s statement seemed to contradict the available evidence.',
  },
  {
    word: 'contribute',
    phonetic: '/kənˈtrɪbjuːt/',
    pos: 'v.',
    meaning: '贡献，捐助，促成',
    example: 'Open source developers contribute code to benefit the entire community.',
  },
  {
    word: 'controversial',
    phonetic: '/ˌkɒntrəˈvɜːʃl/',
    pos: 'adj.',
    meaning: '有争议的，引起争论的',
    example: 'The proposed policy has become a highly controversial topic.',
  },
  {
    word: 'conventional',
    phonetic: '/kənˈvenʃənl/',
    pos: 'adj.',
    meaning: '传统的，惯例的，常规的',
    example: 'Electric cars are gradually replacing conventional gasoline vehicles.',
  },
  {
    word: 'coordinate',
    phonetic: '/kəʊˈɔːdɪneɪt/',
    pos: 'v.',
    meaning: '协调，整合，配合',
    example: 'She was appointed to coordinate activities among the various departments.',
  },
  {
    word: 'crucial',
    phonetic: '/ˈkruːʃl/',
    pos: 'adj.',
    meaning: '至关重要的，关键性的',
    example: 'Continuous innovation is crucial to maintaining business competitiveness.',
  },
  {
    word: 'cumulative',
    phonetic: '/ˈkjuːmjələtɪv/',
    pos: 'adj.',
    meaning: '累积的，渐增的',
    example: 'The cumulative effect of daily learning will yield immense progress.',
  },
  {
    word: 'decade',
    phonetic: '/ˈdekeɪd/',
    pos: 'n.',
    meaning: '十年，十年期',
    example: 'Mobile communications experienced dramatic revolutions in the last decade.',
  },
  {
    word: 'decisive',
    phonetic: '/dɪˈsaɪsɪv/',
    pos: 'adj.',
    meaning: '决定性的，果断的，坚决的',
    example: 'The commander\'s decisive action prevented further casualties.',
  },
  {
    word: 'dedicate',
    phonetic: '/ˈdedɪkeɪt/',
    pos: 'v.',
    meaning: '奉献，致力于，把…献给',
    example: 'Many scientists dedicate their entire lives to medical breakthroughs.',
  },
  {
    word: 'deficient',
    phonetic: '/dɪˈfɪʃnt/',
    pos: 'adj.',
    meaning: '缺乏的，不足的，有缺陷的',
    example: 'A diet deficient in vitamins can cause various health complications.',
  },
  {
    word: 'deliberate',
    phonetic: '/dɪˈlɪbərət/',
    pos: 'adj.',
    meaning: '故意的，深思熟虑的，从容的',
    example: 'The company made a deliberate choice to focus on product quality.',
  },
  {
    word: 'demonstrate',
    phonetic: '/ˈdemənstreɪt/',
    pos: 'v.',
    meaning: '证明，展示，演示',
    example: 'The experiment was designed to demonstrate the new physical principle.',
  },
  {
    word: 'deny',
    phonetic: '/dɪˈnaɪ/',
    pos: 'v.',
    meaning: '否认，拒绝给予，抵赖',
    example: 'No one can deny the profound impact of the Internet on society.',
  },
  {
    word: 'depict',
    phonetic: '/dɪˈpɪkt/',
    pos: 'v.',
    meaning: '描绘，描画，描述',
    example: 'The novel depicts the vibrant life of urban youth in modern cities.',
  },
  {
    word: 'derive',
    phonetic: '/dɪˈraɪv/',
    pos: 'v.',
    meaning: '获得，源于，提取',
    example: 'Many modern English words derive from Latin or Greek roots.',
  },
  {
    word: 'deteriorate',
    phonetic: '/dɪˈtɪəriəreɪt/',
    pos: 'v.',
    meaning: '恶化，退化，变坏',
    example: 'Without proper care, the patient\'s condition may deteriorate rapidly.',
  },
  {
    word: 'differentiate',
    phonetic: '/ˌdɪfəˈrenʃieɪt/',
    pos: 'v.',
    meaning: '区分，区别，辨别',
    example: 'It is essential to differentiate between facts and personal opinions.',
  },
  {
    word: 'dimension',
    phonetic: '/daɪˈmenʃn/',
    pos: 'n.',
    meaning: '维度，尺寸，规模',
    example: 'The breakthrough added an entirely new dimension to the research.',
  },
  {
    word: 'diminish',
    phonetic: '/dɪˈmɪnɪʃ/',
    pos: 'v.',
    meaning: '减少，减小，降低',
    example: 'The difficulties did not diminish his enthusiasm for space exploration.',
  },
  {
    word: 'discipline',
    phonetic: '/ˈdɪsəplɪn/',
    pos: 'n./v.',
    meaning: '纪律，学科，训练',
    example: 'Success in coding requires intense curiosity and persistent discipline.',
  },
  {
    word: 'distinguish',
    phonetic: '/dɪˈstɪŋɡwɪʃ/',
    pos: 'v.',
    meaning: '区别，辨认，使杰出',
    example: 'It is sometimes hard to distinguish truth from clever rumors.',
  },
  {
    word: 'dominate',
    phonetic: '/ˈdɒmɪneɪt/',
    pos: 'v.',
    meaning: '支配，主导，在…占主导地位',
    example: 'Deep learning models currently dominate artificial intelligence research.',
  },
  {
    word: 'drastic',
    phonetic: '/ˈdræstɪk/',
    pos: 'adj.',
    meaning: '严厉的，剧烈的，猛烈的',
    example: 'The city implemented drastic measures to curb severe traffic congestion.',
  },
  {
    word: 'duration',
    phonetic: '/djuˈreɪʃn/',
    pos: 'n.',
    meaning: '持续时间，期间',
    example: 'The total duration of the flight from Beijing to London is 10 hours.',
  },
  {
    word: 'elaborate',
    phonetic: '/ɪˈlæbərət/',
    pos: 'adj./v.',
    meaning: '详尽阐述，精心制作的，复杂的',
    example: 'Could you please elaborate on your proposed implementation strategy?',
  },
  {
    word: 'eliminate',
    phonetic: '/ɪˈlɪmɪneɪt/',
    pos: 'v.',
    meaning: '消除，排除，淘汰',
    example: 'The new algorithm can eliminate repetitive calculations efficiently.',
  },
  {
    word: 'emerge',
    phonetic: '/ɪˈmɜːdʒ/',
    pos: 'v.',
    meaning: '浮现，显露，摆脱',
    example: 'Several promising tech startups emerge during the AI innovation wave.',
  },
  {
    word: 'emphasize',
    phonetic: '/ˈemfəsaɪz/',
    pos: 'v.',
    meaning: '强调，着重，重视',
    example: 'The professor repeatedly emphasize the significance of code clean-up.',
  },
  {
    word: 'enable',
    phonetic: '/ɪˈneɪbl/',
    pos: 'v.',
    meaning: '使能够，使可行',
    example: 'High-speed 5G networks enable real-time autonomous driving applications.',
  },
  {
    word: 'encounter',
    phonetic: '/ɪnˈkaʊntə(r)/',
    pos: 'v./n.',
    meaning: '遇到，遭遇，偶然碰到',
    example: 'Every software developer will encounter unexpected bugs during deployment.',
  },
  {
    word: 'enhance',
    phonetic: '/ɪnˈhɑːns/',
    pos: 'v.',
    meaning: '提高，增强，增进',
    example: 'Reading technical documentation helps enhance your engineering capabilities.',
  },
  {
    word: 'enthusiastic',
    phonetic: '/ɪnˌθjuːziˈæstɪk/',
    pos: 'adj.',
    meaning: '热情的，热心的，热衷的',
    example: 'The students were enthusiastic about participating in the hackathon.',
  },
  {
    word: 'equivalent',
    phonetic: '/ɪˈkwɪvələnt/',
    pos: 'adj./n.',
    meaning: '相等的，等值的，等价物',
    example: 'One kilometer is equivalent to approximately 0.62 miles.',
  },
  {
    word: 'essential',
    phonetic: '/ɪˈsenʃl/',
    pos: 'adj.',
    meaning: '必不可少的，基本的，实质的',
    example: 'Good communication skills are essential for successful team collaboration.',
  },
  {
    word: 'evaluate',
    phonetic: '/ɪˈvæljueɪt/',
    pos: 'v.',
    meaning: '评估，评价，估计',
    example: 'We need to evaluate the model performance using independent test datasets.',
  },
  {
    word: 'evident',
    phonetic: '/ˈevɪdənt/',
    pos: 'adj.',
    meaning: '明显的，显然的，明白的',
    example: 'It is evident that customer satisfaction is directly tied to response speed.',
  },
  {
    word: 'exceed',
    phonetic: '/ɪkˈsiːd/',
    pos: 'v.',
    meaning: '超过，胜过，超出',
    example: 'The quarterly revenue growth is expected to exceed fifteen percent.',
  },
  {
    word: 'exception',
    phonetic: '/ɪkˈsepʃn/',
    pos: 'n.',
    meaning: '例外，除外，异常',
    example: 'The program caught an unhandled exception and safely recovered.',
  },
  {
    word: 'exclusive',
    phonetic: '/ɪkˈskluːsɪv/',
    pos: 'adj.',
    meaning: '独占的，排他的，高档的',
    example: 'The reporter secured an exclusive interview with the AI pioneer.',
  },
  {
    word: 'exhibit',
    phonetic: '/ɪɡˈzɪbɪt/',
    pos: 'v./n.',
    meaning: '展示，显出，展品',
    example: 'The intelligent agent exhibit remarkable reasoning and logic abilities.',
  },
  {
    word: 'expand',
    phonetic: '/ɪkˈspænd/',
    pos: 'v.',
    meaning: '扩大，膨胀，扩张',
    example: 'The tech giant plans to expand its cloud infrastructure globally.',
  },
  {
    word: 'explicit',
    phonetic: '/ɪkˈsplɪsɪt/',
    pos: 'adj.',
    meaning: '明确的，清楚的，直率的',
    example: 'The instruction manual provides explicit guidelines for system maintenance.',
  },
  {
    word: 'exploit',
    phonetic: '/ɪkˈsplɔɪt/',
    pos: 'v.',
    meaning: '开发，利用，开拓',
    example: 'Companies seek to exploit the power of big data for smarter decisions.',
  },
  {
    word: 'extend',
    phonetic: '/ɪkˈstend/',
    pos: 'v.',
    meaning: '延伸，扩展，提供',
    example: 'The university decided to extend the project submission deadline by two weeks.',
  },
  {
    word: 'extract',
    phonetic: '/ɪkˈstrækt/',
    pos: 'v.',
    meaning: '提取，提炼，摘录',
    example: 'Natural language processing algorithms can extract key concepts from text.',
  },
  {
    word: 'feasible',
    phonetic: '/ˈfiːzəbl/',
    pos: 'adj.',
    meaning: '可行的，行得通的，适宜的',
    example: 'The engineering team confirmed that the distributed architecture is feasible.',
  },
  {
    word: 'flexible',
    phonetic: '/ˈfleksəbl/',
    pos: 'adj.',
    meaning: '灵活的，可变通的，有弹性的',
    example: 'A flexible work schedule helps employees balance career and personal life.',
  },
  {
    word: 'fluctuate',
    phonetic: '/ˈflʌktʃueɪt/',
    pos: 'v.',
    meaning: '波动，起伏，涨落',
    example: 'Stock prices fluctuate continuously according to market sentiments.',
  },
  {
    word: 'fundamental',
    phonetic: '/ˌfʌndəˈmentl/',
    pos: 'adj.',
    meaning: '基础的，根本的，基本的',
    example: 'Understanding algorithms is fundamental to mastering computer science.',
  },
  {
    word: 'generate',
    phonetic: '/ˈdʒenəreɪt/',
    pos: 'v.',
    meaning: '生成，产生，引起',
    example: 'Solar panels generate clean electrical energy during sunny daylight hours.',
  },
  {
    word: 'genuine',
    phonetic: '/ˈdʒenjuɪn/',
    pos: 'adj.',
    meaning: '真诚的，真正的，非伪造的',
    example: 'He expressed genuine gratitude to everyone who supported his open source tool.',
  },
  {
    word: 'guarantee',
    phonetic: '/ˌɡærənˈtiː/',
    pos: 'v./n.',
    meaning: '保证，担保，保修单',
    example: 'Automated test suites guarantee that newly added features do not break existing logic.',
  },
]

/**
 * 随机获取 20 道四级题目，并为每道题目自动生成 4 个互斥选项
 */
export function generateCet4Quiz(count = 20): Array<{
  word: string
  phonetic: string
  pos: string
  meaning: string
  example: string
  options: string[]
}> {
  const shuffled = [...CET4_WORDS].sort(() => Math.random() - 0.5)
  const selected = shuffled.slice(0, count)

  return selected.map((item) => {
    // 从其他单词抽取 3 个互斥错误项
    const otherMeanings = CET4_WORDS
      .filter(w => w.meaning !== item.meaning)
      .map(w => w.meaning)
      .sort(() => Math.random() - 0.5)
      .slice(0, 3)

    const options = [item.meaning, ...otherMeanings].sort(() => Math.random() - 0.5)

    return {
      word: item.word,
      phonetic: item.phonetic,
      pos: item.pos,
      meaning: item.meaning,
      example: item.example,
      options,
    }
  })
}
