/**
 * @module dsh-better-sidebar-mcp/scanner/marketplace
 * @description 官方精选热门 MCP 预设模板库
 */

import type { McpMarketplacePreset } from '../types.ts'

export const MCP_PRESETS: McpMarketplacePreset[] = [
  {
    id: 'github',
    name: 'GitHub',
    description: '官方 GitHub 仓库管理、Issue 追踪、PR 检索与代码浏览',
    category: 'developer',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-github'],
    envTemplate: {
      GITHUB_PERSONAL_ACCESS_TOKEN: '',
    },
    docUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/github',
  },
  {
    id: 'sqlite',
    name: 'SQLite Explorer',
    description: '本地 SQLite 数据库查询、结构自省与数据分析',
    category: 'data',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-sqlite', '--db-path', './data.db'],
    docUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite',
  },
  {
    id: 'fetch',
    name: 'Web Fetch & Parser',
    description: '网页抓取、HTML 智能解析与 Markdown 文本提取',
    category: 'web',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-fetch'],
    docUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/fetch',
  },
  {
    id: 'brave-search',
    name: 'Brave Search',
    description: '实时互联网搜索与隐私 Web 知识检索',
    category: 'web',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-brave-search'],
    envTemplate: {
      BRAVE_API_KEY: '',
    },
    docUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search',
  },
  {
    id: 'puppeteer',
    name: 'Puppeteer Browser',
    description: '无头浏览器自动化控制、页面截图与 DOM 交互',
    category: 'web',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-puppeteer'],
    docUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer',
  },
  {
    id: 'postgres',
    name: 'PostgreSQL Manager',
    description: '企业级 PostgreSQL 数据库只读/读写查询与 Schema 探索',
    category: 'data',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-postgres', 'postgresql://user:password@localhost:5432/mydb'],
    docUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/postgres',
  },
  {
    id: 'memory',
    name: 'Knowledge Graph Memory',
    description: '持久化知识图谱与实体关系长期记忆存储',
    category: 'developer',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-memory'],
    docUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/memory',
  },
  {
    id: 'filesystem',
    name: 'Secure Filesystem',
    description: '限定安全目录下的本地文件与目录读写自省',
    category: 'system',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-filesystem', './'],
    docUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem',
  },
  {
    id: 'everything',
    name: 'Everything Sandbox',
    description: '官方全能测试沙箱服务（Prompt、Resources、Tools 综合演示）',
    category: 'developer',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-everything'],
    docUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/everything',
  },
  {
    id: 'git',
    name: 'Git Version Control',
    description: '本地 Git 仓库版本控制、历史记录与分支操作',
    category: 'developer',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-git', './'],
    docUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/git',
  },
]
