import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    width: '100%',
    backgroundColor: 'transparent',
    color: 'inherit',
    fontFamily: 'inherit',
    fontSize: '13px',
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 12px',
    borderBottom: '1px solid var(--dsw-alias-border-subtle, rgba(125, 125, 125, 0.15))',
    backgroundColor: 'var(--dsw-alias-bg-surface, transparent)',
  },
  titleSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontWeight: 600,
    fontSize: '13px',
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  iconButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '26px',
    height: '26px',
    borderRadius: '6px',
    border: '1px solid var(--dsw-alias-border-subtle, rgba(125, 125, 125, 0.15))',
    backgroundColor: 'transparent',
    color: 'var(--dsw-alias-label-secondary, inherit)',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  primaryButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '4px 10px',
    borderRadius: '6px',
    border: 'none',
    backgroundColor: '#3b82f6',
    color: '#ffffff',
    fontSize: '12px',
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'background 0.15s ease',
  },
  searchBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    margin: '8px 10px 4px',
    padding: '5px 8px',
    borderRadius: '6px',
    backgroundColor: 'var(--dsw-alias-bg-subtle, rgba(125, 125, 125, 0.06))',
    border: '1px solid var(--dsw-alias-border-subtle, rgba(125, 125, 125, 0.15))',
  },
  searchInput: {
    flex: 1,
    background: 'transparent',
    border: 'none',
    outline: 'none',
    color: 'inherit',
    fontSize: '12px',
  },
  categoryBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    padding: '4px 10px 8px',
    overflowX: 'auto',
    scrollbarWidth: 'none',
  },
  categoryChip: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '3px 8px',
    borderRadius: '12px',
    border: '1px solid var(--dsw-alias-border-subtle, rgba(125, 125, 125, 0.15))',
    backgroundColor: 'var(--dsw-alias-bg-subtle, rgba(125, 125, 125, 0.04))',
    color: 'var(--dsw-alias-label-secondary, inherit)',
    fontSize: '11px',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    transition: 'all 0.15s ease',
  },
  categoryChipActive: {
    backgroundColor: 'rgba(59, 130, 246, 0.12)',
    borderColor: '#3b82f6',
    color: '#3b82f6',
    fontWeight: 600,
  },
  listContent: {
    flex: 1,
    overflowY: 'auto',
    padding: '4px 10px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  card: {
    display: 'flex',
    flexDirection: 'column',
    gap: '5px',
    padding: '10px 12px',
    borderRadius: '8px',
    backgroundColor: 'var(--dsw-alias-bg-subtle, rgba(125, 125, 125, 0.04))',
    border: '1px solid var(--dsw-alias-border-subtle, rgba(125, 125, 125, 0.12))',
    cursor: 'pointer',
    transition: 'transform 0.15s ease, border-color 0.15s ease, background-color 0.15s ease',
  },
  cardHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '8px',
  },
  cardTitleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontWeight: 600,
    fontSize: '13px',
    color: 'inherit',
  },
  cardDesc: {
    fontSize: '12px',
    color: 'var(--dsw-alias-label-secondary, rgba(125, 125, 125, 0.8))',
    lineHeight: '1.4',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
  },
  tagPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '3px',
    padding: '1px 6px',
    borderRadius: '4px',
    fontSize: '10px',
    fontWeight: 500,
    backgroundColor: 'var(--dsw-alias-bg-subtle, rgba(125, 125, 125, 0.08))',
    color: 'var(--dsw-alias-label-secondary, inherit)',
    border: '1px solid var(--dsw-alias-border-subtle, rgba(125, 125, 125, 0.1))',
  },
  cardActions: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: '4px',
    paddingTop: '6px',
    borderTop: '1px solid var(--dsw-alias-border-subtle, rgba(125, 125, 125, 0.08))',
  },
  badge: {
    padding: '1px 6px',
    borderRadius: '10px',
    fontSize: '10px',
    fontWeight: 600,
    backgroundColor: '#3b82f6',
    color: '#ffffff',
  },
}
