/**
 * @module dsh-better-sidebar-mcp/client/styles
 * @description DSH 规范主题自适应样式表
 */

import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    width: '100%',
    backgroundColor: 'transparent',
    color: 'inherit',
    fontFamily: 'inherit',
    fontSize: '13px',
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 12px',
    borderBottom: '1px solid var(--dsw-alias-border-subtle, rgba(125, 125, 125, 0.15))',
    backgroundColor: 'var(--dsw-alias-bg-surface, transparent)',
  },
  titleSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontWeight: 600,
    fontSize: '13px',
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  iconButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '26px',
    height: '26px',
    borderRadius: '6px',
    border: '1px solid var(--dsw-alias-border-subtle, rgba(125, 125, 125, 0.15))',
    backgroundColor: 'transparent',
    color: 'var(--dsw-alias-label-secondary, inherit)',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  primaryButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '4px 10px',
    borderRadius: '6px',
    border: 'none',
    backgroundColor: '#3b82f6',
    color: '#ffffff',
    fontSize: '12px',
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'background 0.15s ease',
  },
  searchBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    margin: '8px 10px 4px',
    padding: '5px 8px',
    borderRadius: '6px',
    backgroundColor: 'var(--dsw-alias-bg-subtle, rgba(125, 125, 125, 0.06))',
    border: '1px solid var(--dsw-alias-border-subtle, rgba(125, 125, 125, 0.15))',
  },
  searchInput: {
    flex: 1,
    background: 'transparent',
    border: 'none',
    outline: 'none',
    color: 'inherit',
    fontSize: '12px',
  },
  statsBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '4px 10px 4px',
    fontSize: '11px',
    color: 'var(--dsw-alias-label-secondary, #64748b)',
  },
  presetContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '2px 10px 8px',
    position: 'relative',
    userSelect: 'none',
  },
  presetScroll: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    overflowX: 'auto',
    overflowY: 'hidden',
    scrollBehavior: 'smooth',
    scrollbarWidth: 'thin',
    padding: '2px 0',
    flex: 1,
  },
  presetNavBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '18px',
    height: '24px',
    borderRadius: '4px',
    border: '1px solid var(--dsw-alias-border-subtle, rgba(125, 125, 125, 0.15))',
    backgroundColor: 'var(--dsw-alias-bg-surface, rgba(125, 125, 125, 0.06))',
    color: 'var(--dsw-alias-label-secondary, #64748b)',
    cursor: 'pointer',
    fontSize: '11px',
    padding: 0,
    flexShrink: 0,
    transition: 'all 0.15s ease',
  },
  presetChip: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '3px 8px',
    borderRadius: '12px',
    border: '1px solid var(--dsw-alias-border-subtle, rgba(125, 125, 125, 0.15))',
    backgroundColor: 'var(--dsw-alias-bg-subtle, rgba(125, 125, 125, 0.04))',
    color: 'var(--dsw-alias-label-secondary, inherit)',
    fontSize: '11px',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    flexShrink: 0,
    transition: 'all 0.15s ease',
  },
  contentList: {
    flex: 1,
    overflowY: 'auto',
    padding: '4px 10px 14px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  badge: {
    fontSize: '10px',
    padding: '1px 5px',
    borderRadius: '10px',
    backgroundColor: 'rgba(59, 130, 246, 0.12)',
    color: '#3b82f6',
    fontWeight: 600,
  },
}
